/**
 * Tasks list for a project.
 * This route demonstrates the key pattern:
 *   - clientLoader: extracts the URL param only, no data fetching
 *   - TanStack Query hook (generated by Orval): owns all data fetching
 *
 * After running `pnpm generate`, replace the placeholder with:
 *
 *   import { useLoaderData } from "react-router";
 *   import { useGetProjectIdTasks } from "../api/generated/tasks";
 *
 *   export async function clientLoader({ params }: Route.ClientLoaderArgs) {
 *     return { projectId: params.id };
 *   }
 *
 *   export default function ProjectTasksPage() {
 *     const { projectId } = useLoaderData<typeof clientLoader>();
 *     const { data, isLoading } = useGetProjectIdTasks(projectId!);
 *     ...
 *   }
 */
import { useParams, Link } from "react-router";

export default function ProjectTasksPage() {
  const { id } = useParams();

  return (
    <div>
      <Link to={`/projects/${id}`} className="text-blue-600 hover:underline text-sm mb-4 block">
        ← Back to project
      </Link>
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Tasks</h1>
      <p className="text-gray-500">
        Run <code className="bg-gray-100 px-1.5 py-0.5 rounded text-sm">pnpm generate</code> to
        generate the API hooks, then wire them up here.
      </p>
    </div>
  );
}
